server:
  port: 8080

spring:
  application:
    name: management-service

  profiles:
    active: dev

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false

    consumer:
      group-id: management-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: record

sigma:
  event:
    consumer:
      topics: 
        - "Anomaly.event"
        - "sensor-violations"
      groupId: "management-consumer-group"
      subscription:
        - "AnomalyCreated"
        - "SensorViolation"

logging.level.org.springframework.boot.context.properties: DEBUG

grafana:
  url: ${GRAFANA_URL:http://localhost:3000}
  token: ${GRAFANA_TOKEN:}