spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://factory-db.c5g4a4ekcfvb.ap-northeast-2.rds.amazonaws.com:3306/factory_db?sslMode=trust
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
