apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-service
  namespace: management
  labels:
    app: management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-service
  template:
    metadata:
      labels:
        app: management-service
    spec:
      containers:
        - name: management-service
          image: $IMAGE:$IMAGE_TAG
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: s3-secret
            - secretRef:
                name: rdb-secret
          env:
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "management_db"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "sigma-kafka-kafka-bootstrap.default.svc.cluster.local:9092"
            - name: DB_MAX_POOL_SIZE
              value: "5"
            - name: DB_MIN_IDLE
              value: "2"
            - name: SERVER_PORT
              value: "8080"
            - name: GRAFANA_URL
              value: "http://grafana.management.svc.cluster.local:3000"
            - name: GRAFANA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: token
                  optional: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
