name: Deploy Debezium Connector

on:
  workflow_dispatch:
  push:
    branches: [main, feat/ci]
    paths:
      - 'k8s/connector/connector.yaml'
      - '.github/workflows/deploy-connector.yml'

jobs:
  deploy-connector:
    uses: 404-Factory/.github/.github/workflows/reusable-deploy-connector.yml@dev
    with:
      eks-cluster-name: ${{ vars.EKS_CLUSTER_NAME }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
